//! Low-level keyboard hook (Windows) that swallows the hotkey main key's
//! hardware auto-repeat while the long-press action runs.
//!
//! The long press fires while the user still physically holds e.g. Alt+W.
//! The copy simulation must release Alt logically, and from that instant the
//! held W auto-repeats as plain text ("wwww") into whatever has focus —
//! typematic repeat is generated by the keyboard hardware and cannot be
//! stopped, only intercepted. v1 (AutoHotkey) suppressed the hotkey suffix
//! key with its own WH_KEYBOARD_LL hook; this module restores that behavior.

use std::sync::atomic::{AtomicU32, Ordering};

/// Virtual-key code of the configured hotkey's main (non-modifier) key.
/// 0 means unknown/none — suppression is skipped.
static MAIN_VK: AtomicU32 = AtomicU32::new(0);

/// Remember the configured hotkey so `suppress_hotkey_key_until_release`
/// knows which key to swallow. Called from `apply_hotkey`.
pub fn remember_hotkey(hotkey: &str) {
    MAIN_VK.store(main_key_vk(hotkey).unwrap_or(0), Ordering::SeqCst);
}

/// Windows virtual-key code for the hotkey's main key: the last '+'-separated
/// segment of strings like "Alt+W" / "ctrl+shift+F5". Returns None for keys
/// this table doesn't cover (suppression is then skipped, not an error).
pub fn main_key_vk(hotkey: &str) -> Option<u32> {
    let _ = hotkey;
    unimplemented!("main_key_vk not implemented yet")
}

/// Swallow the configured hotkey key's physical key-down events system-wide
/// until the key is physically released (its key-up passes through), or until
/// a safety timeout unhooks unconditionally. Returns once the hook is
/// installed so the caller can safely start synthesizing input. No-op when
/// the key is unknown, the hook fails to install (e.g. blocked by security
/// software), or a suppression is already active.
pub fn suppress_hotkey_key_until_release() {
    imp::suppress_until_release(MAIN_VK.load(Ordering::SeqCst));
}

mod imp {
    use std::sync::atomic::{AtomicU32, Ordering};
    use std::sync::mpsc;
    use windows_sys::Win32::Foundation::{LPARAM, LRESULT, WPARAM};
    use windows_sys::Win32::System::Threading::GetCurrentThreadId;
    use windows_sys::Win32::UI::WindowsAndMessaging::{
        CallNextHookEx, DispatchMessageW, GetMessageW, PostThreadMessageW, SetWindowsHookExW,
        TranslateMessage, UnhookWindowsHookEx, KBDLLHOOKSTRUCT, LLKHF_INJECTED, MSG,
        WH_KEYBOARD_LL, WM_KEYDOWN, WM_KEYUP, WM_QUIT, WM_SYSKEYDOWN, WM_SYSKEYUP,
    };

    /// Key currently being suppressed (0 = hook idle). Doubles as the
    /// "already active" latch so only one hook thread ever runs.
    static TARGET_VK: AtomicU32 = AtomicU32::new(0);
    /// Hook thread id, so the callback / watchdog can end its message loop.
    static HOOK_THREAD: AtomicU32 = AtomicU32::new(0);

    /// How long the hook may live at most, even if the key-up is never seen.
    const SAFETY_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);

    unsafe extern "system" fn hook_proc(code: i32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
        if code >= 0 {
            let info = &*(lparam as *const KBDLLHOOKSTRUCT);
            let target = TARGET_VK.load(Ordering::SeqCst);
            let injected = info.flags & LLKHF_INJECTED != 0;
            if target != 0 && !injected && info.vkCode == target {
                match wparam as u32 {
                    // Hardware auto-repeat of the held key: swallow it so it
                    // cannot type into the focused window (or close a browser
                    // tab as Ctrl+W while our Ctrl is down).
                    WM_KEYDOWN | WM_SYSKEYDOWN => return 1,
                    // Physical release: repeats are over. Let the key-up pass
                    // through and shut the hook down.
                    WM_KEYUP | WM_SYSKEYUP => {
                        TARGET_VK.store(0, Ordering::SeqCst);
                        let tid = HOOK_THREAD.load(Ordering::SeqCst);
                        if tid != 0 {
                            PostThreadMessageW(tid, WM_QUIT, 0, 0);
                        }
                    }
                    _ => {}
                }
            }
        }
        CallNextHookEx(std::ptr::null_mut(), code, wparam, lparam)
    }

    pub(super) fn suppress_until_release(vk: u32) {
        if vk == 0 {
            return;
        }
        // Only one suppression at a time (long presses are serialized anyway).
        if TARGET_VK.swap(vk, Ordering::SeqCst) != 0 {
            return;
        }
        let (ready_tx, ready_rx) = mpsc::channel::<bool>();
        std::thread::spawn(move || unsafe {
            let hook = SetWindowsHookExW(WH_KEYBOARD_LL, Some(hook_proc), std::ptr::null_mut(), 0);
            if hook.is_null() {
                TARGET_VK.store(0, Ordering::SeqCst);
                let _ = ready_tx.send(false);
                return;
            }
            let tid = GetCurrentThreadId();
            HOOK_THREAD.store(tid, Ordering::SeqCst);
            let _ = ready_tx.send(true);

            // Watchdog: never leave a system-wide hook lingering.
            std::thread::spawn(move || {
                std::thread::sleep(SAFETY_TIMEOUT);
                PostThreadMessageW(tid, WM_QUIT, 0, 0);
            });

            // The hook callback runs on this thread while it pumps messages.
            let mut msg: MSG = std::mem::zeroed();
            while GetMessageW(&mut msg, std::ptr::null_mut(), 0, 0) > 0 {
                TranslateMessage(&msg);
                DispatchMessageW(&msg);
            }
            UnhookWindowsHookEx(hook);
            HOOK_THREAD.store(0, Ordering::SeqCst);
            TARGET_VK.store(0, Ordering::SeqCst);
        });
        // Wait for installation so the caller's synthesized modifier release
        // can't race ahead of the suppression.
        let _ = ready_rx.recv_timeout(std::time::Duration::from_millis(200));
    }
}

#[cfg(test)]
mod tests {
    use super::main_key_vk;

    #[test]
    fn maps_letter_main_key_case_insensitively() {
        assert_eq!(main_key_vk("Alt+W"), Some(0x57));
        assert_eq!(main_key_vk("alt+w"), Some(0x57));
        assert_eq!(main_key_vk("Ctrl+Shift+a"), Some(0x41));
    }

    #[test]
    fn maps_digits_and_function_keys() {
        assert_eq!(main_key_vk("Alt+1"), Some(0x31));
        assert_eq!(main_key_vk("Ctrl+F5"), Some(0x70 + 4));
        assert_eq!(main_key_vk("F12"), Some(0x70 + 11));
    }

    #[test]
    fn maps_named_keys() {
        assert_eq!(main_key_vk("Alt+Space"), Some(0x20));
        assert_eq!(main_key_vk("Ctrl+Insert"), Some(0x2D));
    }

    #[test]
    fn unknown_or_empty_keys_yield_none() {
        // 모르는 키는 억제만 생략하고 기능은 계속 동작해야 하므로 None.
        assert_eq!(main_key_vk("Alt+OEM_3"), None);
        assert_eq!(main_key_vk(""), None);
        assert_eq!(main_key_vk("Alt+F99"), None);
    }
}
