//! Low-level keyboard hook (Windows) that swallows the hotkey main key's
//! hardware auto-repeat while the long-press action runs.
//!
//! The long press fires while the user still physically holds e.g. Alt+W.
//! The copy simulation must release Alt logically, and from that instant the
//! held W auto-repeats as plain text ("wwww") into whatever has focus —
//! typematic repeat is generated by the keyboard hardware and cannot be
//! stopped, only intercepted. v1 (AutoHotkey) suppressed the hotkey suffix
//! key with its own WH_KEYBOARD_LL hook; this module restores that behavior.

use std::sync::atomic::{AtomicU32, Ordering};

/// Virtual-key code of the configured hotkey's main (non-modifier) key.
/// 0 means unknown/none — suppression is skipped.
static MAIN_VK: AtomicU32 = AtomicU32::new(0);

/// Remember the configured hotkey so `suppress_hotkey_key_until_release`
/// knows which key to swallow. Called from `apply_hotkey`.
pub fn remember_hotkey(hotkey: &str) {
    MAIN_VK.store(main_key_vk(hotkey).unwrap_or(0), Ordering::SeqCst);
}

/// Windows virtual-key code for the hotkey's main key: the last '+'-separated
/// segment of strings like "Alt+W" / "ctrl+shift+F5". Returns None for keys
/// this table doesn't cover (suppression is then skipped, not an error).
pub fn main_key_vk(hotkey: &str) -> Option<u32> {
    let key = hotkey.rsplit('+').next()?.trim();
    if key.is_empty() {
        return None;
    }
    let upper = key.to_ascii_uppercase();
    match upper.as_bytes() {
        [c @ b'A'..=b'Z'] | [c @ b'0'..=b'9'] => Some(*c as u32),
        _ => match upper.as_str() {
            "SPACE" => Some(0x20),
            "INSERT" => Some(0x2D),
            "DELETE" => Some(0x2E),
            "HOME" => Some(0x24),
            "END" => Some(0x23),
            "PAGEUP" => Some(0x21),
            "PAGEDOWN" => Some(0x22),
            _ => {
                // F1..F24 -> VK_F1 (0x70) ..
                let n: u32 = upper.strip_prefix('F')?.parse().ok()?;
                if (1..=24).contains(&n) {
                    Some(0x70 + n - 1)
                } else {
                    None
                }
            }
        },
    }
}

/// Swallow the configured hotkey key's physical key-down events system-wide
/// until the key is physically released (its key-up passes through), or until
/// a safety timeout unhooks unconditionally. Returns once the hook is
/// installed so the caller can safely start synthesizing input. No-op when
/// the key is unknown, the hook fails to install (e.g. blocked by security
/// software), or a suppression is already active.
pub fn suppress_hotkey_key_until_release() {
    imp::suppress_until_release(MAIN_VK.load(Ordering::SeqCst));
}

mod imp {
    use std::sync::atomic::{AtomicU32, Ordering};
    use std::sync::mpsc;
    use windows_sys::Win32::Foundation::{GetLastError, LPARAM, LRESULT, WPARAM};
    use windows_sys::Win32::System::LibraryLoader::GetModuleHandleW;
    use windows_sys::Win32::System::Threading::{
        GetCurrentThread, GetCurrentThreadId, SetThreadPriority, THREAD_PRIORITY_TIME_CRITICAL,
    };
    use windows_sys::Win32::UI::Input::KeyboardAndMouse::GetAsyncKeyState;
    use windows_sys::Win32::UI::WindowsAndMessaging::{
        CallNextHookEx, DispatchMessageW, GetMessageW, PostThreadMessageW, SetWindowsHookExW,
        TranslateMessage, UnhookWindowsHookEx, KBDLLHOOKSTRUCT, LLKHF_INJECTED, MSG,
        WH_KEYBOARD_LL, WM_KEYDOWN, WM_QUIT, WM_SYSKEYDOWN,
    };

    /// Key currently being suppressed (0 = hook idle). Doubles as the
    /// "already active" latch so only one hook thread ever runs.
    static TARGET_VK: AtomicU32 = AtomicU32::new(0);
    /// Auto-repeat key-downs swallowed in the current session (diagnostic).
    static SWALLOWED: AtomicU32 = AtomicU32::new(0);
    /// Of those, how many carried the LLKHF_INJECTED flag (diagnostic: reveals
    /// a shortcut layer re-injecting the key rather than hardware auto-repeat).
    static SWALLOWED_INJECTED: AtomicU32 = AtomicU32::new(0);

    /// How long the hook may live at most, even if the key is never seen up.
    const SAFETY_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);
    /// How often the watchdog samples the physical key state.
    const POLL_INTERVAL: std::time::Duration = std::time::Duration::from_millis(8);

    unsafe extern "system" fn hook_proc(code: i32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
        if code >= 0 {
            let info = &*(lparam as *const KBDLLHOOKSTRUCT);
            let target = TARGET_VK.load(Ordering::SeqCst);
            // Swallow the held key's key-downs — INJECTED OR NOT — so they can't
            // type into the focused window (or close a browser tab as Ctrl+W
            // while our Ctrl is down). We never synthesize this key ourselves,
            // so blocking injected copies is safe and necessary: the global-
            // shortcut layer re-injects the suppressed key, and those injected
            // key-downs were leaking straight past an earlier `!injected` guard.
            // Key-ups pass through untouched; when to STOP suppressing is
            // decided by polling the physical key state (below), never by a
            // key-up in the stream — repeat artifacts unhooked the hook early.
            if target != 0
                && info.vkCode == target
                && matches!(wparam as u32, WM_KEYDOWN | WM_SYSKEYDOWN)
            {
                SWALLOWED.fetch_add(1, Ordering::SeqCst);
                if info.flags & LLKHF_INJECTED != 0 {
                    SWALLOWED_INJECTED.fetch_add(1, Ordering::SeqCst);
                }
                return 1;
            }
        }
        CallNextHookEx(std::ptr::null_mut(), code, wparam, lparam)
    }

    /// True while the key is physically held down right now.
    unsafe fn key_is_down(vk: u32) -> bool {
        GetAsyncKeyState(vk as i32) as u16 & 0x8000 != 0
    }

    pub(super) fn suppress_until_release(vk: u32) {
        if vk == 0 {
            eprintln!("[keyhook] hotkey main key unknown; auto-repeat suppression skipped");
            return;
        }
        // Only one suppression at a time (long presses are serialized anyway).
        if TARGET_VK.swap(vk, Ordering::SeqCst) != 0 {
            return;
        }
        let (ready_tx, ready_rx) = mpsc::channel::<bool>();
        std::thread::spawn(move || unsafe {
            let hmod = GetModuleHandleW(std::ptr::null());
            let hook = SetWindowsHookExW(WH_KEYBOARD_LL, Some(hook_proc), hmod, 0);
            if hook.is_null() {
                eprintln!(
                    "[keyhook] SetWindowsHookExW failed (err={}); suppression skipped",
                    GetLastError()
                );
                TARGET_VK.store(0, Ordering::SeqCst);
                let _ = ready_tx.send(false);
                return;
            }
            // A low-level keyboard hook whose thread doesn't service the
            // callback within LowLevelHooksTimeout (~300ms) has that event
            // passed through instead of swallowed. Run it real-time so the pump
            // stays responsive under lookup load (as AutoHotkey's hook does).
            SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_TIME_CRITICAL);
            let tid = GetCurrentThreadId();
            SWALLOWED.store(0, Ordering::SeqCst);
            SWALLOWED_INJECTED.store(0, Ordering::SeqCst);
            eprintln!("[keyhook] installed for vk=0x{vk:02X}");
            let _ = ready_tx.send(true);

            // Stop suppressing once the key is PHYSICALLY released — sampled
            // directly, not inferred from the event stream — with a hard safety
            // cap so a system-wide hook can never linger.
            std::thread::spawn(move || {
                let start = std::time::Instant::now();
                loop {
                    std::thread::sleep(POLL_INTERVAL);
                    if !key_is_down(vk) || start.elapsed() >= SAFETY_TIMEOUT {
                        PostThreadMessageW(tid, WM_QUIT, 0, 0);
                        break;
                    }
                }
            });

            // The hook callback runs on this thread while it pumps messages.
            let mut msg: MSG = std::mem::zeroed();
            while GetMessageW(&mut msg, std::ptr::null_mut(), 0, 0) > 0 {
                TranslateMessage(&msg);
                DispatchMessageW(&msg);
            }
            UnhookWindowsHookEx(hook);
            TARGET_VK.store(0, Ordering::SeqCst);
            eprintln!(
                "[keyhook] released; swallowed {} auto-repeat(s) ({} injected)",
                SWALLOWED.load(Ordering::SeqCst),
                SWALLOWED_INJECTED.load(Ordering::SeqCst)
            );
        });
        // Wait for installation so the caller's synthesized modifier release
        // can't race ahead of the suppression.
        let _ = ready_rx.recv_timeout(std::time::Duration::from_millis(200));
    }
}

#[cfg(test)]
mod tests {
    use super::main_key_vk;

    #[test]
    fn maps_letter_main_key_case_insensitively() {
        assert_eq!(main_key_vk("Alt+W"), Some(0x57));
        assert_eq!(main_key_vk("alt+w"), Some(0x57));
        assert_eq!(main_key_vk("Ctrl+Shift+a"), Some(0x41));
    }

    #[test]
    fn maps_digits_and_function_keys() {
        assert_eq!(main_key_vk("Alt+1"), Some(0x31));
        assert_eq!(main_key_vk("Ctrl+F5"), Some(0x70 + 4));
        assert_eq!(main_key_vk("F12"), Some(0x70 + 11));
    }

    #[test]
    fn maps_named_keys() {
        assert_eq!(main_key_vk("Alt+Space"), Some(0x20));
        assert_eq!(main_key_vk("Ctrl+Insert"), Some(0x2D));
    }

    #[test]
    fn unknown_or_empty_keys_yield_none() {
        // 모르는 키는 억제만 생략하고 기능은 계속 동작해야 하므로 None.
        assert_eq!(main_key_vk("Alt+OEM_3"), None);
        assert_eq!(main_key_vk(""), None);
        assert_eq!(main_key_vk("Alt+F99"), None);
    }
}
